# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Mobile_no', models.CharField(max_length=15, unique=True)),
                ('land_ha', models.FloatField(blank=True, max_length=15, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=15, null=True)),
                ('soil_ph', models.FloatField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('yield_tons', models.FloatField(null=True)),
                ('datOfSow', models.DateField(blank=True, null=True)),
                ('pHadv', models.CharField(max_length=150)),
                ('picMsg', models.CharField(max_length=150)),
                ('cropmes', models.CharField(max_length=180)),
                ('recCrop', models.CharField(max_length=260)),
                ('ElecConduc', models.FloatField(blank=True, null=True)),
                ('OrgCarbonP', models.FloatField(blank=True, null=True)),
                ('Nitrogenkgha', models.FloatField(blank=True, null=True)),
                ('Phosphoruskgha', models.FloatField(blank=True, null=True)),
                ('Potassium_kgha', models.FloatField(blank=True, null=True)),
                ('Sulphur_ppm', models.FloatField(blank=True, null=True)),
                ('Zinc_ppm', models.FloatField(blank=True, null=True)),
                ('Boron_ppm', models.FloatField(blank=True, null=True)),
                ('Ironppm', models.FloatField(blank=True, null=True)),
                ('Manganese_ppm', models.FloatField(blank=True, null=True)),
                ('Copper_ppm', models.FloatField(blank=True, null=True)),
                ('Waterph', models.FloatField(blank=True, null=True)),
                ('min2months', models.FloatField(blank=True, null=True)),
                ('max2months', models.FloatField(blank=True, null=True)),
                ('isCurFarm', models.BooleanField(default=False)),
                ('currentCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_2_name', to='datamodel.Crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Place')),
                ('prevCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_1_Name', to='datamodel.Crop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
