# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-24 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('seas_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pH_min', models.FloatField(blank=True, null=True)),
                ('pH_max', models.FloatField(blank=True, null=True)),
                ('min_yieldT', models.FloatField(blank=True, null=True)),
                ('MintempC', models.FloatField(blank=True, null=True)),
                ('MaxtempC', models.FloatField(blank=True, null=True)),
                ('fertilizer', models.CharField(blank=True, max_length=150, null=True)),
                ('growthRegul', models.CharField(blank=True, max_length=230, null=True)),
                ('pick_start', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('interv', models.FloatField(blank=True, null=True)),
                ('max_yieldT', models.FloatField(blank=True, null=True)),
                ('FlowIniti', models.FloatField(blank=True, null=True)),
                ('min_RainMM', models.FloatField(blank=True, null=True)),
                ('max_RainMM', models.FloatField(blank=True, null=True)),
                ('pests', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Lat', models.CharField(blank=True, max_length=30)),
                ('Long', models.CharField(blank=True, max_length=30)),
                ('Pincode', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30)),
                ('datenum', models.IntegerField()),
                ('moonrise', models.CharField(max_length=30)),
                ('moonset', models.CharField(max_length=30)),
                ('sunrise', models.CharField(max_length=30)),
                ('sunset', models.CharField(max_length=30)),
                ('maxtempC', models.FloatField()),
                ('mintempC', models.FloatField()),
                ('rainMM', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('WindSpeedMil', models.FloatField()),
                ('WindGustMil', models.FloatField()),
                ('Winddir16Point', models.CharField(max_length=30)),
                ('WindDesc', models.CharField(max_length=100)),
                ('WindDirdeg', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Place')),
            ],
        ),
    ]
